# Generated by Django 2.1 on 2019-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tittle',
            new_name='title',
        ),
    ]
