# Generated by Django 2.1 on 2019-01-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190127_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='types',
            field=models.CharField(default='Simple', max_length=50),
            preserve_default=False,
        ),
    ]
